name: Linux

on:
  push:
    branches: [ "legacy" ]
  pull_request:
    branches: [ "legacy" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Fetch Dependencies
      run: sudo apt install build-essential git python3 libglew-dev libsdl2-dev curl libcurl4-gnutls-dev libjsoncpp-dev
    - name: Build
      run: make
